import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Model Release Control Center | Hendar Mawan, PhD",
  description: "Decision-first AI code-generation release engineering: baseline/candidate comparison, regression detection, failure analysis and explainable SHIP / INVESTIGATE / HOLD decisions.",
};

const links = [
  ["GitHub Source", "https://github.com/h00w/model-quality-release-gate", "Source of truth for the release policy, React control center, tests and publication automation."],
  ["Hugging Face Space", "https://huggingface.co/spaces/h0000w/model-quality-release-gate", "Canonical Phase 1 interactive demo with six deterministic release scenarios."],
  ["Evaluation Dataset", "https://huggingface.co/datasets/h0000w/model-quality-release-gate", "Public evaluation evidence and normalized result schema."],
  ["Hugging Face Model Card", "https://huggingface.co/h0000w/model-quality-release-gate", "Methodology, release policy and artifact index."],
];

export default function ModelQualityReleaseGatePage(){
 return <>
  <header className="nav"><div className="shell nav-inner"><Link href="/" className="brand">HENDAR<span>.</span></Link><nav className="nav-links"><Link href="/">Portfolio</Link><Link href="/agentic-ai/">Agentic AI Academy</Link><a href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">GitHub ↗</a></nav></div></header>
  <main>
   <section className="hero" style={{paddingTop:140,paddingBottom:70}}><div className="shell"><div style={{maxWidth:980}}><div className="hero-eyebrow">PHASE 1 COMPLETE · AI EVALUATION · RELEASE ENGINEERING</div><h1 className="display" style={{fontSize:"clamp(3rem,7vw,6.5rem)",lineHeight:.92}}>AI Model Release Control Center</h1><div className="hero-role" style={{marginTop:22}}>Evaluate → Compare → Investigate → Gate → Ship</div><p className="muted" style={{maxWidth:860,fontSize:"1.08rem",lineHeight:1.85,marginTop:22}}>A production-oriented evaluation system that turns multidimensional model evidence into an explainable <strong>SHIP / INVESTIGATE / HOLD</strong> decision instead of relying on a single benchmark score.</p><div className="hero-actions" style={{marginTop:30}}><a className="btn btn-primary" href="https://huggingface.co/spaces/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Open Phase 1 Demo ↗</a><a className="btn btn-ghost" href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">View Source ↗</a><a className="btn btn-ghost" href="https://huggingface.co/datasets/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Open Dataset ↗</a></div></div></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">01</div><div className="kicker">Phase 1 outcome</div></div><h2 className="section-title">The first release is a decision system, not a dashboard.</h2></div><div className="card-grid">{[["Executive release view","The first screen answers one question immediately: can this candidate model ship?"],["Baseline vs candidate","Every quality signal is interpreted relative to the current production baseline."],["Regression detection","Higher-is-better and lower-is-better metrics use explicit release tolerances."],["Failure explorer","Individual failures retain category, severity and release-impact context."],["Explainability","The system states why a model is SHIP, INVESTIGATE or HOLD."],["Demo coverage","Six deterministic scenarios exercise healthy, ambiguous and blocking outcomes."]].map(([t,c])=><article className="glass card" key={t}><h3>{t}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{c}</p></article>)}</div></div></section>

   <section className="section"><div className="shell"><div className="section-heading"><div><div className="section-index">02</div><div className="kicker">Release semantics</div></div><h2 className="section-title">A better model can still be the wrong release.</h2></div><div className="card-grid">{[["SHIP","All critical constraints pass and quality is stable or improved."],["INVESTIGATE","A non-critical regression or adverse trade-off requires engineering review."],["HOLD","A critical safety issue or material reliability/correctness regression blocks promotion."]].map(([t,c])=><article className="glass card" key={t}><div className="kicker">{t}</div><h3>{t}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{c}</p></article>)}</div></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">03</div><div className="kicker">Architecture</div></div><h2 className="section-title">Evidence is separated from presentation.</h2></div><div className="glass card" style={{padding:30}}><pre style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>Baseline evaluation     Candidate evaluation{"\n"}        │                     │{"\n"}        └──────────┬──────────┘{"\n"}                   ↓{"\n"}           Metric Aggregation{"\n"}                   ↓{"\n"}          Regression Detection{"\n"}                   ↓{"\n"}            Failure Analysis{"\n"}                   ↓{"\n"}            Release Policy{"\n"}                   ↓{"\n"}        SHIP / INVESTIGATE / HOLD{"\n"}                   ↓{"\n"}       Explanation + evidence export</pre></div></div></section>

   <section className="section"><div className="shell"><div className="section-heading"><div><div className="section-index">04</div><div className="kicker">Phase 1 scenario matrix</div></div><h2 className="section-title">Six reproducible cases make the release policy easy to demonstrate.</h2></div><div className="card-grid">{[["Candidate improves overall","SHIP"],["Latency regression","INVESTIGATE"],["Safety regression","HOLD"],["Code quality regression","HOLD"],["Mixed trade-offs","INVESTIGATE"],["Catastrophic failure","HOLD"]].map(([scenario,decision])=><article className="glass card" key={scenario}><div className="kicker">{decision}</div><h3>{scenario}</h3><p className="muted" style={{fontSize:14,lineHeight:1.75}}>Switch the scenario in the live Space and inspect the metric deltas, release explanation and affected failures.</p></article>)}</div></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">05</div><div className="kicker">Public evidence chain</div></div><h2 className="section-title">Code, methodology, evaluation evidence and live execution are independently inspectable.</h2></div><div className="card-grid">{links.map(([title,href,copy])=><article className="glass card" key={title}><h3>{title}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{copy}</p><a className="btn btn-ghost" href={href} target="_blank" rel="noreferrer">Open ↗</a></article>)}</div></div></section>

   <section className="section"><div className="shell"><div className="callout"><div className="kicker">Connection to Agentic AI Academy</div><h2 className="section-title" style={{marginTop:10}}>Evaluation becomes meaningful when it controls release.</h2><p className="muted" style={{maxWidth:850,lineHeight:1.85}}>The release control center extends the Academy’s evaluation, security and production-engineering work with an explicit production boundary: measurable regressions, deterministic policy, inspectable failures and an accountable promotion decision.</p><div className="hero-actions"><Link className="btn btn-primary" href="/agentic-ai/">Open Agentic AI Academy</Link><a className="btn btn-ghost" href="https://huggingface.co/spaces/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Run Release Gate ↗</a></div></div></div></section>
  </main>
 </>;
}
