import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Model Release Control Center | Hendar Mawan, PhD",
  description: "Production AI model release engineering with real provider evaluation, deterministic safety/correctness checks, optional LLM judging, CI gating, production traces, evidence-linked promotion and historical model registry semantics.",
};

const links = [
  ["GitHub Source", "https://github.com/h00w/model-quality-release-gate", "Source of truth for provider adapters, release policy, evidence generator, CI enforcement, trace schema and registry semantics."],
  ["Hugging Face Space", "https://huggingface.co/spaces/h0000w/model-quality-release-gate", "Reference release gate plus live provider evaluation, trace ingestion and evidence-linked promotion demo."],
  ["Versioned Dataset", "https://huggingface.co/datasets/h0000w/model-quality-release-gate", "Published CodeBench-Safety benchmark versions and reproducible evaluation evidence."],
  ["Methodology Card", "https://huggingface.co/h0000w/model-quality-release-gate", "Release policy, benchmark provenance and publication index."],
];

const phase4 = [
  ["Real provider evaluation", "Server-side Hugging Face inference compares baseline and candidate models without exposing provider tokens to the browser."],
  ["Deterministic safety authority", "Security checks detect injection-prone shell/SQL patterns, unsafe deserialization, weak cryptography and hard-coded secrets."],
  ["Correctness evidence", "Task-aware deterministic checks produce objective correctness evidence without executing untrusted generated code in-process."],
  ["Optional LLM judge", "A judge can add subjective helpfulness/clarity evidence, but cannot override deterministic critical safety or correctness failures."],
  ["Production trace ingestion", "Schema-validated JSONL traces feed operational latency/error evidence into the control plane."],
  ["Model lifecycle registry", "Explicit candidate → approved → production transitions carry the release evidence identity that authorized promotion."],
  ["CI + audit continuity", "Phase 4 reuses Phase 3 machine-readable decisions, manifests, checksums and HOLD enforcement rather than creating a second policy path."],
];

export default function ModelQualityReleaseGatePage(){
 return <>
  <header className="nav"><div className="shell nav-inner"><Link href="/" className="brand">HENDAR<span>.</span></Link><nav className="nav-links"><Link href="/">Portfolio</Link><Link href="/agentic-ai/">Agentic AI Academy</Link><a href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">GitHub ↗</a></nav></div></header>
  <main>
   <section className="hero" style={{paddingTop:140,paddingBottom:70}}><div className="shell"><div style={{maxWidth:980}}><div className="hero-eyebrow">PHASE 4 COMPLETE · PRODUCTION AI · MODEL RELEASE ENGINEERING</div><h1 className="display" style={{fontSize:"clamp(3rem,7vw,6.5rem)",lineHeight:.92}}>AI Model Release Control Center</h1><div className="hero-role" style={{marginTop:22}}>Evaluate → Compare → Investigate → Gate → Promote → Operate</div><p className="muted" style={{maxWidth:900,fontSize:"1.08rem",lineHeight:1.85,marginTop:22}}>A production-oriented model-release control plane connecting real model-provider execution to deterministic safety/correctness evidence, optional LLM judging, machine-readable release policy, CI enforcement, production-trace ingestion and evidence-linked model promotion.</p><div className="hero-actions" style={{marginTop:30}}><a className="btn btn-primary" href="https://huggingface.co/spaces/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Open Phase 4 Control Center ↗</a><a className="btn btn-ghost" href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">Inspect Source ↗</a><a className="btn btn-ghost" href="https://huggingface.co/datasets/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Open Dataset ↗</a></div></div></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">01</div><div className="kicker">Phase 4 outcome</div></div><h2 className="section-title">Evaluation now spans provider execution, release policy and production lifecycle.</h2></div><div className="card-grid">{phase4.map(([t,c])=><article className="glass card" key={t}><h3>{t}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{c}</p></article>)}</div></div></section>

   <section className="section"><div className="shell"><div className="section-heading"><div><div className="section-index">02</div><div className="kicker">Trust boundary</div></div><h2 className="section-title">Real inference without weakening release authority.</h2></div><div className="glass card" style={{padding:30}}><pre style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>Real provider{"\n"}    ↓{"\n"}server-side adapter{"\n"}    ↓{"\n"}normalized output + hashes{"\n"}    ├─ deterministic security checks{"\n"}    ├─ deterministic correctness checks{"\n"}    ├─ latency / provenance{"\n"}    └─ optional subjective LLM judge{"\n"}    ↓{"\n"}Phase 3 evidence + release policy{"\n"}    ↓{"\n"}SHIP / INVESTIGATE / HOLD{"\n"}    ↓{"\n"}candidate → approved → production{"\n"}              or blocked</pre></div><p className="muted" style={{marginTop:18,lineHeight:1.8}}>Provider secrets stay server-side. Generated code is not executed inside the public Space process; a production executable-code evaluator should use an isolated sandbox/worker boundary.</p></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">03</div><div className="kicker">Operational evidence</div></div><h2 className="section-title">Offline benchmark evidence and production traces share the lifecycle boundary.</h2></div><div className="card-grid">{[["Prompt/output provenance","SHA-256 identities make provider outputs referenceable in downstream evidence."],["Trace schema","trace_id, model, latency_ms and status are validated before aggregation."],["Operational metrics","Accepted traces expose error rate and average latency for production-quality investigation."],["Historical registry","Model lifecycle state is explicit instead of relying on an ambiguous latest tag."],["Evidence identity","Every promotion transition records the evidence identifier that authorized it."],["Fail-closed critical safety","Critical deterministic findings route release decisions to HOLD regardless of subjective judge quality."]].map(([t,c])=><article className="glass card" key={t}><h3>{t}</h3><p className="muted" style={{fontSize:14,lineHeight:1.75}}>{c}</p></article>)}</div></div></section>

   <section className="section"><div className="shell"><div className="section-heading"><div><div className="section-index">04</div><div className="kicker">Release governance</div></div><h2 className="section-title">The production path still resolves to one auditable release contract.</h2></div><div className="card-grid">{[["SHIP","Candidate is eligible for evidence-linked promotion."],["INVESTIGATE","No automatic promotion; engineering review is required."],["HOLD","CI release gate fails and promotion routes to blocked."],["Versioned benchmark","CodeBench-Safety definitions evolve by semantic version rather than silent mutation."],["Versioned policy","Evidence identifies the release-policy version used for the decision."],["Tamper evidence","Checksums bind input and decision artifacts for later audit."]].map(([t,c])=><article className="glass card" key={t}><div className="kicker">{t}</div><h3>{t}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{c}</p></article>)}</div></div></section>

   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">05</div><div className="kicker">Public proof chain</div></div><h2 className="section-title">Provider → evaluation → policy → CI → evidence → promotion.</h2></div><div className="card-grid">{links.map(([title,href,copy])=><article className="glass card" key={title}><h3>{title}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{copy}</p><a className="btn btn-ghost" href={href} target="_blank" rel="noreferrer">Open ↗</a></article>)}</div></div></section>

   <section className="section"><div className="shell"><div className="callout"><div className="kicker">Connection to Agentic AI Academy</div><h2 className="section-title" style={{marginTop:10}}>Production AI is a lifecycle system, not a model benchmark.</h2><p className="muted" style={{maxWidth:880,lineHeight:1.85}}>This project demonstrates the Academy’s production-engineering throughline: real provider outputs become normalized evidence; deterministic safety and correctness remain authoritative; CI applies release policy; operational traces feed investigation; and promotion is tied back to auditable evidence.</p><div className="hero-actions"><Link className="btn btn-primary" href="/agentic-ai/">Open Agentic AI Academy</Link><a className="btn btn-ghost" href="https://github.com/h00w/model-quality-release-gate/actions/workflows/release-gate.yml" target="_blank" rel="noreferrer">Inspect Release Gate CI ↗</a></div></div></div></section>
  </main>
 </>;
}
