import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Model Quality Release Gate | Hendar Mawan, PhD",
  description: "AI code-generation evaluation and release engineering: baseline/candidate comparison, regression detection, failure analysis and explainable SHIP / INVESTIGATE / HOLD decisions.",
};

const links = [
  ["GitHub Source", "https://github.com/h00w/model-quality-release-gate", "Policy engine, React dashboard, tests, CI and versioned publication source."],
  ["Hugging Face Space", "https://huggingface.co/spaces/h0000w/model-quality-release-gate", "Interactive model evaluation and real-inference surface."],
  ["Evaluation Dataset", "https://huggingface.co/datasets/h0000w/model-quality-release-gate", "Reproducible evaluation cases and result schema."],
  ["Hugging Face Model Card", "https://huggingface.co/h0000w/model-quality-release-gate", "Methodology, release policy and artifact index."],
];

export default function ModelQualityReleaseGatePage(){
 return <>
  <header className="nav"><div className="shell nav-inner"><Link href="/" className="brand">HENDAR<span>.</span></Link><nav className="nav-links"><Link href="/">Portfolio</Link><Link href="/agentic-ai/">Agentic AI Academy</Link><a href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">GitHub ↗</a></nav></div></header>
  <main>
   <section className="hero" style={{paddingTop:140,paddingBottom:70}}><div className="shell"><div style={{maxWidth:980}}><div className="hero-eyebrow">AI EVALUATION · RELEASE ENGINEERING</div><h1 className="display" style={{fontSize:"clamp(3rem,7vw,6.5rem)",lineHeight:.92}}>Model Quality Release Gate</h1><div className="hero-role" style={{marginTop:22}}>Evaluate. Compare. Detect regressions. Decide whether an AI coding model is ready to ship.</div><p className="muted" style={{maxWidth:860,fontSize:"1.08rem",lineHeight:1.85,marginTop:22}}>A production-oriented evaluation system that turns multidimensional model evidence into an explainable <strong>SHIP / INVESTIGATE / HOLD</strong> decision instead of relying on a single headline benchmark.</p><div className="hero-actions" style={{marginTop:30}}><a className="btn btn-primary" href="https://huggingface.co/spaces/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Run Live Evaluation ↗</a><a className="btn btn-ghost" href="https://github.com/h00w/model-quality-release-gate" target="_blank" rel="noreferrer">View Source ↗</a><a className="btn btn-ghost" href="https://huggingface.co/datasets/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Open Dataset ↗</a></div></div></div></section>
   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">01</div><div className="kicker">Why it matters</div></div><h2 className="section-title">A model can improve quality and still become unsafe, unreliable or too slow to ship.</h2></div><div className="card-grid">{[["Quality","Helpfulness and code-generation correctness are measured against a baseline."],["Safety","Security regressions and critical unsafe outputs can block release."],["Reliability","Malformed outputs, failures and consistency regressions are explicit gates."],["Performance","Latency is treated as a release constraint rather than hidden inside a quality average."],["Evidence","Failures can be inspected and exported instead of reduced to a single score."],["Decision","Deterministic policy converts evidence into SHIP, INVESTIGATE or HOLD."]].map(([t,c])=><article className="glass card" key={t}><h3>{t}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{c}</p></article>)}</div></div></section>
   <section className="section"><div className="shell"><div className="section-heading"><div><div className="section-index">02</div><div className="kicker">Architecture</div></div><h2 className="section-title">One policy engine, multiple evaluation surfaces.</h2></div><div className="glass card" style={{padding:30}}><pre style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>Model / API outputs{"\n"}↓{"\n"}Evaluation Provider{"\n"}↓{"\n"}Normalized EvaluationResult{"\n"}↓{"\n"}Metrics → Regression Detection → Failure Analysis{"\n"}↓{"\n"}Release Gate{"\n"}↓{"\n"}SHIP / INVESTIGATE / HOLD{"\n"}↓{"\n"}React UI · Hugging Face Space · CI · future API</pre></div></div></section>
   <section className="section section-soft"><div className="shell"><div className="section-heading"><div><div className="section-index">03</div><div className="kicker">Public evidence chain</div></div><h2 className="section-title">Code, methodology, evaluation data and live execution are independently inspectable.</h2></div><div className="card-grid">{links.map(([title,href,copy])=><article className="glass card" key={title}><h3>{title}</h3><p className="muted" style={{lineHeight:1.78,fontSize:14}}>{copy}</p><a className="btn btn-ghost" href={href} target="_blank" rel="noreferrer">Open ↗</a></article>)}</div></div></section>
   <section className="section"><div className="shell"><div className="callout"><div className="kicker">Connection to Agentic AI Academy</div><h2 className="section-title" style={{marginTop:10}}>Evaluation is the release boundary between capability and production trust.</h2><p className="muted" style={{maxWidth:850,lineHeight:1.85}}>The release gate extends the Academy’s evaluation, security and production-engineering modules with a concrete model-quality artifact: measurable regressions, explicit tolerances, failure inspection and a deterministic release policy.</p><div className="hero-actions"><Link className="btn btn-primary" href="/agentic-ai/">Open Agentic AI Academy</Link><a className="btn btn-ghost" href="https://huggingface.co/spaces/h0000w/model-quality-release-gate" target="_blank" rel="noreferrer">Run Release Gate ↗</a></div></div></div></section>
  </main>
 </>;
}
